import { Inter } from "next/font/google";
import { Poppins } from 'next/font/google'
import localfont from "next/font/local"
import SmoothScrolling from "@/components/SmoothScrolling";
import CustomCursor from '@/components/CustomCursor'

import "./globals.css";

const mori = localfont({
  src: [
    {
      path: "../public/fonts/PPMori-SemiBold.otf",
      weight: "600"
    },
    {
      path: "../public/fonts/PPMori-Regular.otf",
      weight: "400"
    },
    {
      path: "../public/fonts/PPMori-Extralight.otf",
      weight: "300"
    },
  ],
  variable: "--font-mori"
})

const poppins = Poppins({ 
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600"],
})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${mori.variable} font-mori`}>
      <body className={poppins.className}>
        <CustomCursor />
        <SmoothScrolling>{children}</SmoothScrolling>
      </body>
    </html>

  );
}