import { Inter } from "next/font/google";
import localfont from "next/font/local"

import "./globals.css";

const mori = localfont({
  src: [
    {
      path: "../public/fonts/PPMori-Regular.otf",
      weight: "400"
    },
  ],
  variable: "--font-mori"
})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${mori.variable} font-mori`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
